[project]
name = "fuel-oracle"
version = "0.1.0"
authors = ["dferrer"]
entry = "main.sw"
edition = "2021"
license = "Apache-2.0"

[dependencies]
fuels = "0.14"
fuels-abigen-macro = "0.14"
fuel-core = "0.8"
fuel-gql-client = "0.8"
tokio = { version = "1.12", features = ["rt", "macros"] }